server:
  port: 18081 # 服务端口号

spring:
  cloud:
    nacos:
      discovery: # 注册中心配置
        server-addr: 192.168.0.101:8848 # nacos 注册中心地址
    sentinel: # 限流配置
      transport:
        dashboard: 192.168.0.101:8080 # sentinel 客户端地址
        port: 8719 # 服务与 dashboard 进行交互的端口

  zipkin: # 链路追踪配置
    base-url: http://192.168.0.101:9411 # zipkin 地址
    discovery-client-enabled: false # 是否监控 zipkin 本身的请求
    sender:
      type: web # 链路数据以什么方式返送给 zipkin. web 使用 http 的形式发送
  sleuth: # 采集率配置
    sampler:
      probability: 1 # 采集率, 默认是 百分之10 生产时使用, 开发应该设置为 1 采集全部请求

  datasource: # MySQL
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.101:3306/guli_pms?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai # 连接协议
    username: root
    password: root

  redis: # Redis
    host: 192.168.0.101
    port: 6379
    password: root

feign: # feign
  sentinel:
    enabled: true # 开启 feign 的 sentinel 功能

mybatis-plus: # mybatis-plus 配置
  mapper-locations: classpath:mapper/pms/**/*.xml # 映射文件地址 classpath 就是 resources
  type-aliases-package: com.atguigu.gmall.pms.entity # 别名包扫描
  global-config:
    db-config:
      id-type: auto # id 策略, 生产应该使用分布式 id. auto 数据库自增

logging: # 查看执行 SQL
  level: # 级别
    com.atguigu.gmall.pms: debug # debug 模式